### PR TITLE
Clarifies sprint user docs that confused users

### PR DESCRIPTION
**Pull request by mradcliffe**
Making review changes from #95.

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for stepping back in there @mradcliffe ! One of our priorities this year is to have everything buttoned down *before* Drupalcon with some time for burning flash drives.

**Comment by rfay** [comment]
Looks like the testing on Windows will need some love.

**Comment by mradcliffe** [comment]
Thanks. Yes, I'm putting more time back into this with Brian soonish.

**Comment by mradcliffe** [comment]
I can't remember. Does the buildkite configuration run both the package build and the install or only take the artifacts from circleci and run the installer and sprint tools?

**Comment by rfay** [comment]
Builds and installs - you can look at https://github.com/drud/quicksprint/blob/master/.buildkite/test.sh - I'll try to fix it later this week. We have a release tomorrow so will be attending to that first.

**Comment by mradcliffe** [comment]
I tried running package_drupal_script.sh, but I didn't have jq (easily obtained) so it failed immediately. Not sure if that's the issue on buildkite.

**Comment by mradcliffe** [comment]
Packager fails because zip isn't available (git for windows does not package that).

Was buildkite's thing ever working or maybe it was silently failing?

**Comment by rfay** [comment]
Windows successful now (after retries). Not sure what was wrong, but we'll keep an eye on it and if it's a particular testbot, we'll be able to solve it. I reorganized the required checks and retried the circleci build.

**Review by rfay — APPROVED** [review]
This looks good to me, thanks. So we should close #95 as everything there is covered?

**Comment by mradcliffe** [comment]
Yes, that's correct. Since I opened it, you can merge.

**Pull request merged**
