### PR TITLE
Adds licenses for docker images, docker ce and ddev and copyright info

### PR DESCRIPTION
**Pull request by mradcliffe**
Re: issue #2.

I am not a lawyer.

### CODE REVIEW

**Comment by mradcliffe** [comment]
Also ping @rickmanelius

**Comment by rickmanelius** [comment]
Reviewing now. I did a significant amount of work with our legal team, so I'll serve as a proxy and raise a question if necessary.

**Review by rickmanelius — CHANGES_REQUESTED** [review]
Hi @mradcliffe. This is great! A few suggestions (I can fork and modify if you'd prefer).

* There's a small formatting difference in spacing for the different Apache2 licenses. Since they are all the same content-wise, it might make sense to fix that spacing or just copy. 
* I think we should prepend "LICENSE-" on all the files so that it's easier/more obvious as to what they are and people can feel free to visually skip by them or dive into each. Otherwise, as an end-user I would be confused as to what each file was until I viewed them each individually.

**Comment by mradcliffe** [comment]
Good point on prepending LICENSE- to make it less confusing to a user as to what these text files are.

Talked to @rickmanelius about the formatting differences. I Think that's OK since those files are coming from their respective repositories.

**Review by rickmanelius — APPROVED** [review]
LGTM +1

**Review by rfay — APPROVED** [review]
This seems great to me. I'll pull it after the CLA is signed.

**Comment by mradcliffe** [comment]
Closing for #11

**Comment by rfay** [comment]
Next time it's probably easier to just amend the commits with the right email and force-push.

**Pull request closed without merging**
