### PR TITLE
Get latest docker toolbox and git for windows, fixes #94

### LINKED ISSUE #94: Automatically determine latest docker toolbox release and download link
Currently we have the docker-toolbox (for windows) download link hard-wired into the package_drupal_script.sh. So it's already out of date now that 18.06-1 is out. We need to determine it automatically instead; the api makes this pretty easy, as in https://github.com/drud/ddev/blob/master/install_ddev.sh#L15-L18 (although using jq -r is easier than the technique there.)

### PR DESCRIPTION
**Pull request by rfay**
* Use github API to determine latest docker-toolbox and git-for-windows version for download.
* Stop bundling ddev_windows.tar.gz, which I don't think anybody (should) use any more.

To review, download the artifacts created in circleci and see if they are the right ones.

### CODE REVIEW

**Comment by mradcliffe** [comment]
I tried to extract the tar.gz artifact, but I was getting an error. I'm redownloading and trying again.

**Comment by mradcliffe** [comment]
```
$ tar zxf "drupal_sprint_package.v0.2.2-6-g4b0e5e7(1).tar.gz"
tar: This does not look like a tar archive
tar: Skipping to next header
tar: A lone zero block at 105448
tar: Exiting with failure status due to previous errors
```

Not sure if this is an error with the circleci artifact system, but I know the build process works and there's nothing in the diff that would change the way that tar works.

Trying again with the zip.

**Comment by rfay** [comment]
Hmm, it's huge. Maybe download failed? I got it and have no trouble.  (Looks like you downloaded the same thing twice? Maybe try the other one?) I'm also able to extract just fine.

```
rfay@rfay-mbp-2017:~/Downloads$ tar -tzf drupal_sprint_package.v0.2.2-6-g4b0e5e7.tar.gz
drupal_sprint_package/
drupal_sprint_package/licenses/
drupal_sprint_package/licenses/LICENSE-drud-dev-router.txt
drupal_sprint_package/licenses/LICENSE-drud-docker-phpmyadmin.txt
drupal_sprint_package/licenses/LICENSE-docker-community-edition.txt
drupal_sprint_package/licenses/LICENSE-drud-mariadb-local.txt
```

And note that there are certain download environments that try to automatically ungzip for you. Do a `file drupal_sprint_package.v0.2.2-6-g4b0e5e7(1).tar.gz` or `file drupal_sprint_package.v0.2.2-6-g4b0e5e7.tar.gz` to see what the "file" utility thinks about that thing.  And check the [sha256](https://747-123502111-gh.circle-artifacts.com/0/artifacts/drupal_sprint_package.v0.2.2-6-g4b0e5e7.tar.gz.sha256.txt) to see if it was working right.  On macOS `shasum -a 256 drupal_sprint_package.v0.2.2-6-g4b0e5e7.tar.gz`

**Comment by mradcliffe** [comment]
I confirmed that the latest versions of Docker were in the zip:

* Docker for Windows and Docker for Mac at 2.0.0 (nice, I guess that's supported now 🙌. I haven't had a chance to use the new versioning scheme yet) 
* DockerToolbox 18.09.

**Comment by rfay** [comment]
Yeah, it's just that they have a "docker desktop" that includes docker 18.09.1. Not sure why they rebranded the "docker desktop".

**Review by mradcliffe — APPROVED** [review]

**Pull request merged**
