### PR TITLE
Changes to using git HTTPS URL per https://drupal.org/gitauth (#69)

### PR DESCRIPTION
**Pull request by mradcliffe**
https://drupal.org/gitauth

### CODE REVIEW

**Comment by rfay** [comment]
I don't see anything in that article about git:// being changed.  It remains one of the best unauthenticated and reliable techniques for public repos.

**Comment by mradcliffe** [comment]
Hmm, it's the firewall where I am at blocking git URLs.

That also could be a good reason to change to either `ssh://git@git.drupal.org` (new pattern) or `https://git.drupal.org`.

**Comment by rfay** [comment]
ssh is problematic, won't work for lots of people, and is blocked by lots of firewalls.
You win on https, because it is overall better for firewalls.  So 👍 for https urls.

**Review by rfay — APPROVED** [review]
This is fine then, switching to https should make it work in a majority of cases. I was going to say it didn't really matter because this is *packaging* time, but the *remote* then gets used by our users.

**Pull request merged**
