### PR TITLE
[#42] Changed webserver ports to 8080 and 8443 to avoid collisions with host services, fixes #42

### LINKED ISSUE #42: Breaks when user has mysql already in the system
when running: start_clean.sh or start_sprint.sh 
```
Network ddev_default is external, skipping 
Failed to start sprint-20180408-2046: Unable to listen on required ports, localhost port 80 is in use,
Troubleshooting suggestions at https://ddev.readthedocs.io/en/latest/users/troubleshooting/#unable-listen 
```
have mariadb running from homebrew on socket.

### PR DESCRIPTION
**Pull request by BrianGilbert**
Fixes #42 

Also added https url to output of start_clean and README.txt

### CODE REVIEW

**Comment by rfay** [comment]
This is going to turn out OK, but I haven't manually tested yet, and want to wait until it's rebased on top of the circleci tests. Maybe we can even add a circleci test that actually tests the port.

**Comment by rfay** [comment]
Just needs rebase and I can manually test in the morning. If you authorize me, I can also pull it if it's good.

**Comment by BrianGilbert** [comment]
@rfay happy for you to merge when ready

**Comment by rfay** [comment]
Manually tested on macOS, looks good. Will get it in and test on Windows as in the windows PR tests after rebase.

**Pull request merged**
